### ISSUE TITLE
Not working in Debian 8

### ISSUE THREAD

**Issue by Plorenzo** [sayem314/Ghost-over-Caddy#1]
I'm trying to run the script in a fresh VPS with Debian 8.8 and the following error appears:
`     Error: This script only supports Ubuntu, Debian and CentOS.`

**Comment by sayem314** [comment]
I'll take a look at this. I'm using on Debian, works fine.

**Comment by Plorenzo** [comment]
Some more info, maybe is useful:

```
Operating System: Debian GNU/Linux 8 (jessie)
Kernel: Linux 3.16.0-4-amd64
Architecture: x86-64
Virtualization: kvm
```

**Comment by sayem314** [comment]
Thanks! It's midnight here, so I'll analyze the script tomorrow and check why on Debian 8.8 it is not working. :)

**Comment by sayem314** [comment]
Hi there, I've tried to find the issue and everything seems to working on my side. I don't have Debian 8.8 server hence can't really test it, however it should work on any Debian 8.x

Can you plz run the below command and output here?
`lsb_release -si`
`lsb_release -sr`

**Comment by Plorenzo** [comment]
sure. 

There you go: 
<img width="306" alt="screen shot 2017-05-09 at 12 18 17" src="https://cloud.githubusercontent.com/assets/4695692/25846309/a93a4b66-34b1-11e7-8914-6fd7b79bdf3f.png">

**Comment by sayem314** [comment]
Everything seems perfect. Not sure why it shouldn't work!

**Comment by sayem314** [comment]
DigitalOcean added Debian 8.8 droplet, I've tried on 8.8 now, and it worked without an issue.
