### ISSUE TITLE
Caddy not running

### ISSUE THREAD

**Issue by fakeid30** [sayem314/Ghost-over-Caddy#4]
I am trying to run your script on an Amazon EC2, My site is www.nirjhor.me and my IP Address is : 34.209.215.39

Here is my route 53 : 
![screenshot_20170905_142335](https://user-images.githubusercontent.com/26362832/30051983-d0e71ee0-9245-11e7-982b-1f3f5b1c893e.png)

So I tested it with nginx, after that I removed nginx and used your script , 

`sudo bash setup-ghost.sh www.nirjhor.me`

Here's my info_ghost:

[info_ghost](https://pastebin.com/UutHyPmX
)
And here's my Caddyfile : 

[Caddyfile](https://pastebin.com/uQFFRwde
)
I can't even run caddy, it's showing caddy not installed. What am I doing wrong ?

**Comment by fakeid30** [comment]
This project isn't using ghost CLI it seems, it's trying to install the LTS branch.

**Comment by fakeid30** [comment]
I installed ghost with nginx in nirjhor.me , but there's no easy way to setup caddy there now . Can you point me to the right direction?

**Comment by sayem314** [comment]
No idea with amazon services. I have tested this on a test blog and it seems to be working. Can you try on fresh Debian 8/9?

**Comment by fakeid30** [comment]
@sayem314 I'm running one in https://nirjhor.me right now, I installed using ghost-cli , have you tried on ghost cli or old method (npm production)? 

if on ghost-cli, can you share your final caddyfile that reverse proxied the nginx ghost-cli set up by itself? Thanks!

**Comment by sayem314** [comment]
I have not tried ghost-cli and I do not use nginx.

The script use npm method which works fine for me. What OS are you running?

**Comment by fakeid30** [comment]
@sayem314 npm installs the LTS version, not the current one, so not recommended by ghost authors

Ubuntu 16.04

**Comment by sayem314** [comment]
Try now please. https://github.com/sayem314/Ghost-over-Caddy/commit/93afdf6a776841b4493cfd8c2095f06c036f7424 should fix your issue with Caddy!
